name: 'mkachi-blog-deploy-action'
description: 'Action to deploy my blog with github action'

inputs:
  ACCESS_TOKEN:
    description: 'your access token'
    required: true
    default: ''

  GITHUB_TOKEN:
    description: 'your github token'
    required: true
    default: ''

  FOLDER:
    description: 'deploy file path'
    required: true
    default: 'build'

  BRANCH:
    description: 'deploy branch'
    required: true
    default: 'master'

runs:
  using: 'node12'
  main: 'src/index.js'
